{{- $root := . }}
{{- range .Values.workers }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: |-
   {{ include "awsmachinetemplate.name" $root }}-{{ .name }}
spec:
  template:
    spec:
      {{- if not (quote .amiID | empty) }}
      ami:
        id: {{ .amiID }}
      {{- end }}
      imageLookupFormat: {{ .imageLookup.format }}
      imageLookupOrg: "{{ .imageLookup.org }}"
      imageLookupBaseOS: {{ .imageLookup.baseOS }}
      instanceType: {{ .instanceType }}
      # Instance Profile created by `clusterawsadm bootstrap iam create-cloudformation-stack`
      iamInstanceProfile: {{ .iamInstanceProfile }}
      cloudInit:
        # Makes CAPA use k0s bootstrap cloud-init directly and not via SSM
        # Simplifies the VPC setup as we do not need custom SSM endpoints etc.
        insecureSkipSecretsManager: true
      {{- range $id := .securityGroupIDs }}
      additionalSecurityGroups:
        - id: {{ $id }}
      {{- end }}
      publicIP: {{ $root.Values.publicIP }}
      rootVolume:
        size: {{ .rootVolumeSize }}
{{- end }}